# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "souffle"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Toft"]
  s.date = "2012-12-10"
  s.description = "An orchestrator for describing and building entire systems with Chef"
  s.email = "joshtoft@gmail.com"
  s.executables = ["souffle"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CHANGELOG.md",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "bin/souffle",
    "features/souffle.feature",
    "features/step_definitions/souffle_steps.rb",
    "features/support/env.rb",
    "lib/souffle.rb",
    "lib/souffle/application.rb",
    "lib/souffle/application/souffle-server.rb",
    "lib/souffle/config.rb",
    "lib/souffle/daemon.rb",
    "lib/souffle/dns.rb",
    "lib/souffle/dns/rackspace.rb",
    "lib/souffle/dns/zerigo.rb",
    "lib/souffle/exceptions.rb",
    "lib/souffle/http.rb",
    "lib/souffle/log.rb",
    "lib/souffle/node.rb",
    "lib/souffle/node/runlist.rb",
    "lib/souffle/node/runlist_item.rb",
    "lib/souffle/node/runlist_parser.rb",
    "lib/souffle/polling_event.rb",
    "lib/souffle/provider.rb",
    "lib/souffle/provider/aws.rb",
    "lib/souffle/provider/rackspace.rb",
    "lib/souffle/provider/vagrant.rb",
    "lib/souffle/provisioner.rb",
    "lib/souffle/provisioner/node.rb",
    "lib/souffle/provisioner/system.rb",
    "lib/souffle/server.rb",
    "lib/souffle/ssh_monkey.rb",
    "lib/souffle/state.rb",
    "lib/souffle/system.rb",
    "lib/souffle/template.rb",
    "lib/souffle/templates/Vagrantfile.erb",
    "lib/souffle/version.rb",
    "spec/config/example.json",
    "spec/config/example.rb",
    "spec/config_spec.rb",
    "spec/log_spec.rb",
    "spec/node/runlist_parser_spec.rb",
    "spec/node/runlist_spec.rb",
    "spec/node_spec.rb",
    "spec/provider_spec.rb",
    "spec/providers/aws_provider_spec.rb",
    "spec/providers/vagrant_provider_spec.rb",
    "spec/provisioner_spec.rb",
    "spec/spec_helper.rb",
    "spec/system_spec.rb",
    "spec/template_spec.rb",
    "spec/templates/example_template.erb"
  ]
  s.homepage = "http://github.com/seryl/souffle"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "An orchestrator for describing and building entire systems with Chef"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yajl-ruby>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<eventmachine>, ["~> 1.0.0"])
      s.add_runtime_dependency(%q<amqp>, ["~> 0.9.7"])
      s.add_runtime_dependency(%q<state_machine>, ["~> 1.1.2"])
      s.add_runtime_dependency(%q<em-ssh>, ["~> 0.4.0"])
      s.add_runtime_dependency(%q<em-synchrony>, ["~> 0.2.0"])
      s.add_runtime_dependency(%q<right_aws>, ["~> 3.0.4"])
      s.add_runtime_dependency(%q<tilt>, ["~> 1.3.3"])
      s.add_runtime_dependency(%q<mixlib-cli>, [">= 1.2.2"])
      s.add_runtime_dependency(%q<mixlib-config>, [">= 1.1.0"])
      s.add_runtime_dependency(%q<mixlib-log>, [">= 1.3.0"])
      s.add_runtime_dependency(%q<thin>, ["~> 1.4.1"])
      s.add_runtime_dependency(%q<rack>, ["~> 1.4.1"])
      s.add_runtime_dependency(%q<sinatra>, ["~> 1.3.2"])
      s.add_runtime_dependency(%q<fog>, ["~> 1.7.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.10.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
      s.add_development_dependency(%q<redcarpet>, ["~> 2.1.1"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<ruby-graphviz>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<yajl-ruby>, ["~> 1.1.0"])
      s.add_dependency(%q<eventmachine>, ["~> 1.0.0"])
      s.add_dependency(%q<amqp>, ["~> 0.9.7"])
      s.add_dependency(%q<state_machine>, ["~> 1.1.2"])
      s.add_dependency(%q<em-ssh>, ["~> 0.4.0"])
      s.add_dependency(%q<em-synchrony>, ["~> 0.2.0"])
      s.add_dependency(%q<right_aws>, ["~> 3.0.4"])
      s.add_dependency(%q<tilt>, ["~> 1.3.3"])
      s.add_dependency(%q<mixlib-cli>, [">= 1.2.2"])
      s.add_dependency(%q<mixlib-config>, [">= 1.1.0"])
      s.add_dependency(%q<mixlib-log>, [">= 1.3.0"])
      s.add_dependency(%q<thin>, ["~> 1.4.1"])
      s.add_dependency(%q<rack>, ["~> 1.4.1"])
      s.add_dependency(%q<sinatra>, ["~> 1.3.2"])
      s.add_dependency(%q<fog>, ["~> 1.7.0"])
      s.add_dependency(%q<rspec>, ["~> 2.10.0"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
      s.add_dependency(%q<redcarpet>, ["~> 2.1.1"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<ruby-graphviz>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<yajl-ruby>, ["~> 1.1.0"])
    s.add_dependency(%q<eventmachine>, ["~> 1.0.0"])
    s.add_dependency(%q<amqp>, ["~> 0.9.7"])
    s.add_dependency(%q<state_machine>, ["~> 1.1.2"])
    s.add_dependency(%q<em-ssh>, ["~> 0.4.0"])
    s.add_dependency(%q<em-synchrony>, ["~> 0.2.0"])
    s.add_dependency(%q<right_aws>, ["~> 3.0.4"])
    s.add_dependency(%q<tilt>, ["~> 1.3.3"])
    s.add_dependency(%q<mixlib-cli>, [">= 1.2.2"])
    s.add_dependency(%q<mixlib-config>, [">= 1.1.0"])
    s.add_dependency(%q<mixlib-log>, [">= 1.3.0"])
    s.add_dependency(%q<thin>, ["~> 1.4.1"])
    s.add_dependency(%q<rack>, ["~> 1.4.1"])
    s.add_dependency(%q<sinatra>, ["~> 1.3.2"])
    s.add_dependency(%q<fog>, ["~> 1.7.0"])
    s.add_dependency(%q<rspec>, ["~> 2.10.0"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
    s.add_dependency(%q<redcarpet>, ["~> 2.1.1"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<ruby-graphviz>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end
